### ISSUE TITLE
Issue #1: User can see their Car

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML Page 
- [x] Set background to green
- [x] Set up a container class
- [x] Add image of race car to top of the page using absolute positioning
- [x] Double check code works
- [x] Fix all styling issues 
- [x] Remove unnecessary styling
- [x] Send to Cody for review
