### ISSUE TITLE
Issue #2: User can turn their car

### ISSUE THREAD

**Issue by SharjeelSIqbal** [SharjeelSIqbal/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create 3 CSS rulesets with rotate 90 degrees and rotate -90 degrees and rotate 180 degrees
- [x] Add a event handler for the key down event that takes in user input 
- [x] The event handler will assign a class to the race car that will change it's direction
- [x] when W A S D are hit the car should be rotate to the the relative positions 
- [ ] Create a position variable that keeps track of what position the car is currently in
- [ ] Update that position anytime one of the keys is hit
- [x] Check to see if code works 
- [x] Clean up code and remove unnecessary styling
- [x] Send to Cody for review
